// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.tqz.grpc.demo.proto;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string result = 2;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 2;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
